from vcScript import *
import os 
import os.path
import time
import csv


if True : 
  #---------------------------------------------------------#
  # This behaviour collects and logs the data generated by  #
  # the components in the layout                            #
  #                                                         #
  #---------------------------------------------------------#

  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # Folder where data is saved
  output_dir = "CSV"
  current_dir = os.getcwd()
  # path to the folder where the ouput csv files are generated
  path = os.path.join(current_dir, output_dir)

  sim = getSimulation()
  app = getApplication()

  # list of components in the layout
  components = app.Components 

  # data is written in the csv file every STEP_ITER
  STEP_ITER = 100 #100

  # column names
  column_names = ['Iteration','Timestamp','Transmitter', 'Receiver', 'Message Type', 'Communication Type', 'Period','Data Size', 'Latency', 'Reliability',  'Confirmation']#'Communication Tecnology',->> NO SE USA 
  
  list_comms = []

  # counters
  count_register = 0
  count_iter = 1

  check_file = 0


  # At the end of the simulation, write all data in "list_comms" to the output file
  def OnStop():
    exportDataComunication()
    

  def OnStart():
    global check_file, count_iter
    check_file = 0
    count_iter = 1
    
  def OnSignal(signal):
    global count_iter, count_register
    timeStamp = sim.SimTime
    
    signalList = signal.Value.split(';')
    
    emitter = signalList[0]  # transmitter 
    receiver = signalList[1] # receiver 
    msgType = signalList[2]  # msg type
    comType = signalList[3]  # comm type (periodic or aperiodic data)
    period = signalList[4] # period 
    datasize = signalList[5] # data size
    latency = signalList[6] # latency requirement
    reliability = signalList[7] # reliability requirement
    comTech = signalList[8]  # wireless “ wl” or wired “l”.
    msgValue = signalList[9] # for future use
    ackRequired = signalList[10] # ack required or not - 1(True) o 0(False)
    
    
    if not ((emitter == 'EDGE' or emitter == 'M3 Gage CMM') and (receiver == 'EDGE' or receiver =='M3 Gage CMM')):
      row_i = [count_iter,timeStamp, emitter, receiver, msgType,comType, period, datasize,latency,reliability,ackRequired]
      list_comms.append(row_i) 
      
      if msgType == 'MeasuringCommands' or msgType == 'QualityResult':
        print(row_i)
      #list_comms=list_comms+row_i
    count_register += 1
    
    # export data every STEP_ITER iters
    if count_register == STEP_ITER:
      exportDataComunication()
      count_register = 0
    
    count_iter += 1
    
  # export data 
  def exportDataComunication():
    global check_file
    
    # create csv file
    if not os.path.exists(path):
      os.makedirs(path)
    
    #print("Output path:", path)
    
    if check_file == 0: #first time the file is openned 
      # open file
      f = open(os.path.join(path, "data_communications.csv"), "w")
      
      # delimiter used in the csv file
      state_writer = csv.writer(f, delimiter=",", lineterminator='\n')
      
      state_writer.writerow(column_names)
      
      for row_i in list_comms:
        state_writer.writerow(row_i)
        
      list_comms[:] = []
      # the first time the file is opened, we update the check_file variable
      check_file += 1
      f.close()
    else:
      # open to add a new row
      f = open(os.path.join(path, "data_communications.csv"), "a")
      
      # delimiter used in the csv file
      state_writer = csv.writer(f, delimiter=",", lineterminator='\n')
      
      for row_i in list_comms:
        state_writer.writerow(row_i)
      
      list_comms[:] = []
      f.close()  
else: 
  from vcScript import *
  from vcScript import *
  from vcHelpers.Robot2 import * 
  import csv
  import os.path
  import time
  import vcMatrix 
  from vcHelpers.Selection import *
  import os
  
  